// 공통 error

export const COMMON_ERROR = {
  BAD_REQUEST: "COMMON400",
  VALIDATION: "COMMON400_VALIDATION",
  TYPE: "COMMON400_TYPE",
  FORMAT: "COMMON400_FORMAT",
  PARAM: "COMMON400_PARAM",
  UNAUTHORIZED: "COMMON401",
  FORBIDDEN: "COMMON403",
  NOT_FOUND: "COMMON404",
  INTERNAL_SERVER: "COMMON500",
  SERVICE_UNAVAILABLE: "COMMON503",
} as const;

export const AUTH_ERROR = {
  TYPE_MISMATCH: "AUTH400_TYPE_MISMATCH",
  INVALID: "AUTH401_INVALID",
  EXPIRED: "AUTH401_EXPIRED",
  MALFORMED: "AUTH401_MALFORMED",
  SIGNATURE: "AUTH401_SIGNATURE",
  UNSUPPORTED: "AUTH401_UNSUPPORTED",
  EMPTY_CLAIMS: "AUTH401_EMPTY_CLAIMS",
  INVALID_REFRESH: "AUTH401_INVALID_REFRESH",
  REFRESH_MISSING: "AUTH401_REFRESH_MISSING",
  REFRESH_MISMATCH: "AUTH401_REFRESH_MISMATCH",
  KAKAO_TOKEN: "AUTH401_KAKAO_TOKEN",
  WITHDRAWN: "AUTH403_WITHDRAWN",
  FORBIDDEN: "AUTH403_FORBIDDEN",
  USER_NOT_FOUND: "AUTH404_USER",
  KAKAO_API: "AUTH500_KAKAO_API",
} as const;

export const POST_ERROR = {
  NOT_FOUND: "POST404_1",
} as const;

export const USER_ERROR = {
  INVALID_INTEREST: "USER400_1",
  ALREADY_WITHDRAWN: "USER400_2",
  NOT_FOUND: "USER404_1",
} as const;

export const ACTIVITY_ERROR = {
  BOOKMARK_NOT_FOUND: "ACTIVITY404_1",
  ALREADY_BOOKMARKED: "ACTIVITY409_1",
} as const;

export type CommonErrorCode = (typeof COMMON_ERROR)[keyof typeof COMMON_ERROR];
export type AuthErrorCode = (typeof AUTH_ERROR)[keyof typeof AUTH_ERROR];
export type PostErrorCode = (typeof POST_ERROR)[keyof typeof POST_ERROR];
export type UserErrorCode = (typeof USER_ERROR)[keyof typeof USER_ERROR];
export type ActivityErrorCode =
  (typeof ACTIVITY_ERROR)[keyof typeof ACTIVITY_ERROR];

export type ErrorCode =
  | CommonErrorCode
  | AuthErrorCode
  | PostErrorCode
  | UserErrorCode
  | ActivityErrorCode;
